name: projetoipet
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.23.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.10.0
  provider: ^6.0.0
  fluttertoast: ^8.0.9
  firebase_messaging: ^14.7.7
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.5+3
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
