name: projetoipet
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.2.10
  firebase_core: ^2.23.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.10.0
  provider: ^6.0.0
  fluttertoast: ^8.0.9
  firebase_messaging: ^14.0.0  # Atualize para a versão mais recente
  flutter_local_notifications: ^17.2.2
  image_picker: ^0.8.5+3
  firebase_storage: ^11.7.7
  percent_indicator: ^4.2.2
  flutter_launcher_icons: ^0.9.2
  google_mobile_ads: ^3.0.0 # Verifique se há uma versão mais recente
  badges: ^3.1.2

flutter_native_splash:
  color: "#ffffff"  # Cor de fundo da splash screen
  image: assets/ipet.png  # Caminho para a imagem de splash
  android: true  # Habilitar para Android
  ios: true  # Habilitar para iOS
  fullscreen: true  # Opção para tela cheia


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:  
    uses-material-design: true  
    assets:
        - assets/ipet.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/ipet.png" # Caminho da sua imagem do ícone